---
output:
  word_document:
    reference_docx: manuscriptstyle_pce2.docx
  pdf_document: default
  html_document:
    number_sections: yes
---

```{r, results='asis', echo=FALSE, warning=FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
```

Prof Daniel Epron
\
Editor
\
Tree Physiology

\
\
We are grateful for the opportunity to resubmit our manuscript. We thank the editor for providing insightful comments to improve our manuscript. We have responded in detail to each comment, which has improved the overall quality of the manuscript. Below, we have itemized our response to each comment from the editor.

\
- *Comment: 1. It seems that there are two different effects: rooting volume and container/free rooting. And it seems that the latter is dominating and the clear relations with rooting volume are often missing... ignoring this later treatment may deeply change your way of interpreting the results. Even the stats are strongly influenced by this treatment (effect on residual error for example).*

\
*Response*: We agree with the editor's comments that the effects of soil volume have not been properly accounted for in several places in the manuscript. Particularly in the discussion we have clarified the nature of the effect type, where soil volume effects were often been over-emphasized. We agree that the stats are strongly influenced by the Free seedling, but this is also representative of the observed effects of root restriction on *A*~sat~, TNC and leaf N across all containers throughout all measurement campaigns. We feel that addressing individual effects of specific volume treatments would overly complicate the paper and combining all soil volume treatment effects would not improve our interpretation of the results.

\
- *Comment: 2. L42: you may have mentioned here the other C loss such as exudation, VOC...*

\
*Response*: Editorial change made.  We have included more examples of C losses beyond respiration.  The rest of the paragraph is also adjusted to discuss "C loss" as a more general inclusive term.

\
- *Comment: 3. L212: you may give the temperature range during the respiration measurement*

\
*Response*: Temperature range for dark respiration measurements added to methods

\
- *Comment: 4. L226 and 229: typing errors*

\
*Response*: editorial change made

\
- *Comment: 5. L230: I don’t understand your response to the reviewer ‘Unfortunately, we do not have available C concentration data for plant tissues’. As soon as you get N, you may get C easily when using a Carlo Erba CE1110 elemental analyser.*

\
*Response*: The reviewer asked for C concentration data for the whole plant instead of assuming 50% for woody plant tissues.  We only have C and N data for leaves and roots.  We therefore use the 50% assumption to convert dry seedling biomass to final seedling C.

\
- *Comment: 6. L253-254: R, expressed in gC d-1 is not a mass based leaf respiration. And it is not clear that “leaf respiration is included in the calculation of P”. If it is included, it should not be subtracted again. To get the daily C gain of the seedling, what it is missing there is the night respiration of the foliage and the respiration of the other plant organ. So I guess G is not the daily C gain but the daily C uptake (or gross C gain versus net C gain). But it needs to be clarified.*

\
*Response*: The editor makes several good points here. We have re-written the equation to better describe the way daily total leaf net C gain (*P*~day~) was calculated. We have also removed the statement "Leaf respiration is included in the calculation of *P*." and added a accurate description of how the area based respiration component was calculated at each 15 minute interval in the modelling of leaf net photosynthesis rates.

\
- *Comment: 7. L264: How do simulated An values fit with measured *A*~sat~?*

\
*Response*: It is difficult to accurately compare spot measurements of *A*~sat~ at saturating light inside the gas exchange cuvette with modelled values of *A*~n~ that are estimated over continually fluctuating meteorological conditions over 120 days. With simple modelling exercise, using Licor conditions and measured photosynthetic parameters the estimated rates are slightly higher than observed rates of *A*~sat~. Importantly, this does not effect the overall patterns of decreased CUE in containerized seedlings.

\
- *Comment: 8. L288: CUE is the ratio of net C gain (Pn) to gross C gain (Pg): CUE = Pn/Pg. With Pn=Pg-R, with R the respiration of the seedling. In your calculation CUE is the ratio of produced biomass divided by net leaf C gain. Leaf respiration is subtracted so that daily net leaf C gain is Pg-Rleaf. It is clear at the end that CUE is in your case proportion of modelled cumulative net leaf C gain allocated to observed seedling biomass. But it might be confusing for readers so you may try to improve this part by introducing earlier this notion of net leaf C gain, give a clear definition of leaf An. And at several place, it is not clear in leaf An is on a leaf area basis or at the whole plant basis.*

\
*Response*: We agree with each of the editors points here.  With comment #6 we have now clearly defined the "total net leaf C gain term".  As the editor points out there are several places where leaf *A*~n~ is discussed inappropriately, especially in the discussion.  Throughout the manuscript we have revised use of terms for C gain to accurately reflect either measured photosynthesis rates (*A*~sat~), leaf level rates of net photosynthesis (*A*~n~) or modelled cumulative total net leaf C gain (*P*~day~).

\
- *Comment: 9. L326: two digits is enough: 𝑥 = 0.90, 95 % CI = [0.85,1.12].*

\
*Response*: editorial change made

\
- *Comment: 10. L348: Asat can be added in Table 3 and Fig 4 removed*

\
*Response*: editorial change made.

\
- *Comment: 11. L349-350: These sentences are confusing: does the first sentence refer to *A*~max~ on a leaf area basis. Please clarify.*

\
*Response*: We agree with the editor here.  We have introduced a new term *A*~mass~ to represent *A*~max~ on a mass basis.  This should help easily distinguish between the two variables in the text and is now consistent with Figure 4.

\
- *Comment: 12. L351: I will not say that A~mass~ is highly correlated with both leaf N~f~ and leaf starch, when it only accounts for 28% and 11% of the total variations.*

\
*Response*: editorial change made (removed "highly")

\
- *Comment: 13. L359: I am not convinced that Amax was positively correlated with final harvest biomass. The correlation is driven by the free rooting values. Variation in A~mass~ across rooting volume does not reflect those of biomass in the last point is removed. It means that the co-variation is not so much driven by soil volume. The only clear effect is between container/ free rooting. But it is no more a correlation.*

\
*Response*: This point was overlooked by the authors. This statement has been removed from the results section.

\
- *Comment: 14. L365-366: Remove citations from the results section. Move that sentence in the discussion if it is really needed (I don’t think so).*

\
*Response*: editorial change made

\
- *Comment: 15. L394: Leaf A~n~ (an leaf area basis) or whole plant C gain? Please clarify.*

\
*Response*: editorial change made.  Change *A*~n~ to *A*~sat~ (measured values)

\
- *Comment: 16. L395: not whole plant respiration loss, because leaf respiration is already accounted. So this is something that ‘non-leaf whole plant respiration’.*

\
*Response*: editorial change made

\
- *Comment: 17. L410: this is not true. There is large reduction in biomass related to container size, but not so much effect of container size on A~max~.*

\
*Response*: We have revised this statement to make the point that reductions in measured *A*~sat~ and seedling allometry occurred simultaneously during early measurement campaigns, and these reductions where sustained throughout the experiment.

\
- *Comment: 18. L413: what is A~n~ here? Leaf area or whole plant based?*

\
*Response*: editorial change made.  Changed *A*~n~ to *A*~sat~ (measured values).  

\
- *Comment: 19. L430-431. Correlation between leaf N and A~n~ (what is it?) has not been shown in the result sections.*

\
*Response*: We have corrected *A*~n~ to *A*~mass~, which is reported in the results section.

\
- *Comment: 20. L434: the connexion between root N and N uptake is not trivial.*

\
*Response*: We agree with the editor. We have changed this sentence to give a quantitative description of root N content differences between roots of Free seedlings and seedlings in containers (+15 %). 

\
- *Comment: 21. L441: You did not measure available soil N pool but total soil N, which is different. It would have been interesting to know if microbial N mineralization is affected by the containers or not. The key might not be at the plant level but at the microbe level. And what about other nutrients such as available P?*

\
*Response*: We agree with the editor's comments. There is convincing evidence that nutrient uptake was negatively affected in this experiment but the mechanism is yet unidentified. Understanding the processes by which belowground sink manipulation manifests belowground will be important for future experiments using local soils. We hope that this data-set and experimental design can aid in future experiments to further investigate the mechanisms underpinning belowground sink limitation.

\
- *Comment: 22. L443: again, what is A~n~? And please show us the evidence of a sink limitation on A~n~ of seedlings in container. There is not so much effect of container size on leaf photosynthetic parameter in Table 3*

\
*Response*: editorial change made.  Changed *A*~n~ to *A*~sat~ (measured values). As with comment #10, *A*~sat~ values are also added in Table 3 to show reductions in measured leaf level photosynthesis in containerized seedlings.

\
- *Comment: 23. L449: I am not convinced that the decline in A~max~ is correlated with higher starch content, at least not across the different container size. This is not really an effect of rooting volume but again container versus free soil.*

\
*Response*: We agree with the editor. The use of *A*~max~ was incorrectly used here.  We have edited this sentence to include the correlation with *A*~mass~ and starch, which is described in the results.

\
- *Comment: 24. L477: It is not true that “increases in specific root length were detected in several of the soil volume treatments” It is detected in only one, and not in the smallest one.*

\
*Response*: We have corrected this statement in the discussion to more accurately reflect the observed results.

\
- *Comment: 25. L483: There is no reduction in leaf photosynthesis due to the restricted soil volume, according to the data you reported in Table 3. Make clear what is leaf A~n~. The reduction in whole plant assimilation may mainly be due to a reduction in plant leaf area, which in fact is only evident for the largest soil volume. Final plant leaf area can be added in table 1 with stats. It will be helpful as it is not so easy to visualize differences on figure 1.*

\
*Response*: We have added both measured harvested leaf area and *A*~sat~ into Table 1 and 3, respectively.  Both *A*~sat~ and leaf area were significantly reduced in seedlings in containers compared to the free seedlings. Leaf *A*~n~ was also replaced with "photosynthetic parameters".

\
- *Comment: 26. L477: L483-484: I disagree that reductions in A~max~ and biomass were strongly correlated. The correlation is driven by high value of the free soil. R2 will drop from 0.88 to 0.32 if you remove this last treatment.*

\
*Response*: editorial change made. We have removed the word "strongly"

\
- *Comment: 27. L486: Again, CUE does not really decrease with belowground limitation. There is no effect of rooting volume on CUE if you don’t include free rooting values (R2 cue~container volume = 0.003). There is an effect container/ free rooting, but this effect is not related to the volume of the container, so not clearly related to belowground sink limitation.*

\
*Response*: We have changed this sentence to more accurately reflect the modelling results by removing reference to "belowground sink limitation" and stating that CUE was reduced in containerized seedlings.


