Summary stats for leaf mass area
========================================================

```{r,include=FALSE}
#source functions and packages
source("functions and packages/functions.R")
source("functions and packages/load packages.R")
```


```{r}
#read in plot design, lma data, merge
plotsumm <- read.csv("raw data/plot_summary.csv")
plotsumm$ID <- paste(plotsumm$plot, plotsumm$pot, sep = "-")

lma <- read.csv("raw data/seedling leaf mass area.csv")
lma$ID <- paste(lma$plot, lma$pot, sep = "-")
lma <- merge(lma, plotsumm[3:4], all=TRUE)
lma$volume <- as.factor(lma$volume)

#run function to add campaign dates, caluclate sla
lma <- add_campaign_date(lma)
lma$sla <- with(lma, area/mass)

#remove missing values
lma_noNA <- subset(lma, !is.na(sla))

#subset with only sla and parameters of lm
lma_lm <- subset(lma_noNA, select = c("ID", "volume", "campaign", "sla"))
#----------------------------------------------------------------------------------------------
#Visualize changes in SLA across campaigns (Date messes things up so stay with campaign# (interval=2wks))

#function to create groupData set
grp_func <- function(dfr){
  
  sub_dfr <- subset(dfr, select = c("ID", "campaign", "sla"))
  lma.new <- groupedData(sla ~ campaign|ID, data=sub_dfr)
}
#create groupdData objects by volume
groupData_ls<- dlply(lma_lm, .(volume) , grp_func)
#generate trellis plots
lapply(groupData_ls, plot)

#----------------------------------------------------------------------------------------------
#fit seperate linear regression models for each pot through time, grouped by volume
LMlist_func <- function(dfr){
  
  sub_dfr <- subset(dfr, select = c("ID", "campaign", "sla"))
  lma.new <- groupedData(sla ~ campaign|ID, data=sub_dfr)
  models_ID <- lmList(sla ~ campaign,  data=lma.new)
}

#run LMlist for all pots, split by volume
sla_stats_ls<- dlply(lma_lm, .(volume) , LMlist_func)    

#return coefs and CI(need to add a 'ID' name column)
ldply(sla_stats_ls, coef)
#plot confidence intervals
lapply(sla_stats_ls, function(x) plot(intervals(x)))



```

